import React, {useState, useEffect} from 'react'
import { Loader, Cards, FormField } from '../components'


const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPost, setAllPost] = useState(null);
  const [searchText, setsearchText] = useState('')
  const [searchedResults, setSearchedResults] = useState(null);
  const [searchTimeout, setSearchTimeout] = useState(null);
  
  const RenderCards =({data, title})=>{
    if (data?.length > 0) {
      return (data.map((post)=> <Cards key={post._id} {...post}/>));
    }
    return(
      <h1 className='mt-5 font-bold text-black text-xl uppercase'>{title}</h1>
    );
  };

  useEffect(()=>{
    const fetchPost = async()=>{
      setLoading(true);
      try {
        const response = await fetch('http://localhost:8080/api/v1/post',{
        method:'GET',
        headers:{
          'Content-Type':'application/json'
        },
      })
      if (response.ok) {
        const result = await response.json();

        setAllPost(result.data.reverse());
      }
      } catch (error) {
        alert(error);
      }
      finally{
        setLoading(false);
      }
    }
    fetchPost();
  },[]);
  const handleSearchChange = (e)=>{
    clearTimeout(searchTimeout);

    setsearchText(e.target.value);

    setSearchTimeout(
    setTimeout(()=>{
      const searchResult = allPost.filter((item)=> 
      item.name.toLowerCase().includes(searchText.toLowerCase()) || 
      item.prompt.toLowerCase().includes(searchText.toLowerCase()));
      setSearchedResults(searchResult);
      
    },500))
  }
  return (
   <section className='mx-auto max-w-2xl'>
    <div>
      <h1 className='font-extrabold text-[#222328] text-[32px]'>
        The Community Posts
      </h1>
      <p className='mt-2 text-[#666e75] text-[16px] max-w[500px]'>
        Here are the Awesome images generated by the Dall-e
      </p>
    </div>

    <div className='mt-16'>
      <FormField
        labelName="Search Posts"
        type="text"
        name="text"
        placeholder="Enter the name to search the post"
        value={searchText}
        handleChange={handleSearchChange}
      />
    </div>

    <div className='mt-10'>
        {loading ? ( 
          <div className='flext justify-center'>
            <Loader/>
          </div>
        ) :(
          <>
            {searchText && (
              <h1 className='font-medium text-black text-xl mb-3'>
                Showing result for <span className='text-[#222328]'>{searchText}</span>
              </h1>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards 
                  data={searchedResults}
                  title="no result found"
                />
              ):(
                <RenderCards
                data={allPost}
                title="no post found"
                />
              )
              }
            </div>
          </>
        )
        }
    </div>
   </section>
  )
}

export default Home